
CREATE SEQUENCE IF NOT EXISTS SEQ_GATEWAY_ID START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS GATEWAY (
    SERIAL_NUMBER   NUMBER(19,0) DEFAULT SEQ_GATEWAY_ID.NEXTVAL NOT NULL,
    NAME            VARCHAR(50) NOT NULL UNIQUE,
    IP_ADDRESS      VARCHAR(15) NOT NULL UNIQUE,
    CONSTRAINT PK_GATEWAY_ID PRIMARY KEY (SERIAL_NUMBER)
);

CREATE TABLE IF NOT EXISTS DEVICE (
    UID                     VARCHAR(255) NOT NULL,
    VENDOR                  VARCHAR(50) NOT NULL,
    CREATED_AT              TIMESTAMP NOT NULL,
    STATUS                  VARCHAR(7) NOT NULL,
    GATEWAY_SERIAL_NUM      NUMBER(19,0) NOT NULL,
    CONSTRAINT  PK_DEVICE_ID PRIMARY KEY (UID),
    CONSTRAINT  CHECK_STATUS CHECK STATUS IN ('ONLINE', 'OFFLINE'),
    CONSTRAINT  FK_GATEWAY_SRL_NUM FOREIGN KEY (GATEWAY_SERIAL_NUM) REFERENCES GATEWAY (SERIAL_NUMBER)
);